import { ensureSchema } from './schema.js';
import { randomToken, tokenHash, ensurePlIdentity, resolveCharacterIdentity, storeImage, verifyRoomAdmin, parentRoomForLog, bumpRoomRevision, deleteR2Prefix } from './data-model.js';

const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const safeBody=async request=>{try{return await request.json()}catch{return null}};
const iconUrl=key=>{if(!key)return'';const hash=String(key).replace(/^r2:/,'').split('/').pop();return `/api/player-master/icon/${encodeURIComponent(hash)}`};
const roomHub=(env,roomId)=>env.ROOMS?env.ROOMS.get(env.ROOMS.idFromName(roomId)):null;
const notify=(ctx,roomId,action,data=null)=>{const hub=roomHub(ctx.env,roomId);if(!hub)return;const excludeClientId=String(ctx.request.headers.get('x-realtime-client')||'').slice(0,100);ctx.waitUntil(hub.fetch('https://room/notify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action,data,excludeClientId})}).catch(()=>{}))};
const ensureRoom=(db,id)=>db.prepare('SELECT * FROM room WHERE room_id=?').bind(id).first();
const ensureLog=(db,id)=>parentRoomForLog(db,id);

async function identity(env,body){
  const plId=String(body?.authorId||'').slice(0,120);if(!plId)return{plId:'',characterId:null};
  const old=await env.DB.prepare('SELECT pl_name FROM pl WHERE pl_id=?').bind(plId).first();
  const type=String(body?.personaType||'PL').toUpperCase();
  const plName=String(body?.authorName||body?.plName||old?.pl_name||(type==='PL'?body?.personaName:'PL')||'PL').trim().slice(0,80)||'PL';
  const plIconKey=await storeImage(env.LOGS,String(body?.plIcon||''),'pl-icons');
  await ensurePlIdentity(env.DB,plId,plName,{plIconKey});
  if(type==='PL')return{plId,characterId:null};
  const characterIconKey=await storeImage(env.LOGS,String(body?.personaIcon||''),'character-icons');
  const ch=await resolveCharacterIdentity(env.DB,plId,String(body?.personaName||''),type,{plName,iconKey:characterIconKey,characterId:body?.characterId});
  return{plId,characterId:ch?.character_id||null};
}

async function roomPayload(env,room){
  const logs=(await env.DB.prepare('SELECT log_id,log_name,scenario_title,spoiler_enabled,log_sort_order,created_at FROM log WHERE room_id=? ORDER BY log_sort_order,created_at').bind(room.room_id).all()).results||[];
  const people=(await env.DB.prepare(`SELECT lp.log_id,c.character_id,c.character_name,c.character_type,c.character_icon_key,c.matrix_icon_key,p.pl_id,p.pl_name FROM log_participant lp JOIN character c ON c.character_id=lp.character_id JOIN pl p ON p.pl_id=c.pl_id JOIN log l ON l.log_id=lp.log_id WHERE l.room_id=? ORDER BY lp.participant_sort_order,lp.created_at,c.character_name`).bind(room.room_id).all()).results||[];
  const map=new Map();for(const p of people){const a=map.get(p.log_id)||[];a.push({authorId:p.pl_id,personaId:p.character_id,plName:p.pl_name,name:p.character_name,icon:iconUrl(p.matrix_icon_key||p.character_icon_key),baseIcon:iconUrl(p.character_icon_key),matrixIcon:iconUrl(p.matrix_icon_key)});map.set(p.log_id,a)}
  return{id:room.room_id,name:room.room_name,createdAt:room.created_at,logs:logs.map((l,i)=>({roomId:l.log_id,title:l.log_name||'LOG',order:Number(l.log_sort_order)||i,spoiler:!!l.spoiler_enabled,scenarioTitle:l.scenario_title||'',scenarioParticipants:(map.get(l.log_id)||[]).map(p=>p.name).join(' / '),createdAt:l.created_at,participants:map.get(l.log_id)||[]}))};
}

async function commentRows(env,roomId,viewer,type,targetId=null){
  const where=['c.room_id=?','c.comment_target_type=?'],args=[viewer,roomId,type];if(targetId!==null){where.push('c.comment_target_id=?');args.push(targetId)}
  const r=await env.DB.prepare(`SELECT c.*,p.pl_name,p.pl_icon_key,ch.character_name,ch.character_type,ch.character_icon_key,(SELECT COUNT(*) FROM comment_reaction cr WHERE cr.comment_id=c.comment_id) like_count,EXISTS(SELECT 1 FROM comment_reaction cr WHERE cr.comment_id=c.comment_id AND cr.author_pl_id=?) liked_by_me FROM comment c JOIN pl p ON p.pl_id=c.author_pl_id LEFT JOIN character ch ON ch.character_id=c.author_character_id WHERE ${where.join(' AND ')} ORDER BY c.created_at,c.comment_id`).bind(...args).all();return r.results||[];
}
async function toggleReaction(env,id,authorId){if(!authorId)return null;await ensurePlIdentity(env.DB,authorId,'PL');const old=await env.DB.prepare('SELECT 1 FROM comment_reaction WHERE comment_id=? AND author_pl_id=?').bind(id,authorId).first();if(old)await env.DB.prepare('DELETE FROM comment_reaction WHERE comment_id=? AND author_pl_id=?').bind(id,authorId).run();else await env.DB.prepare('INSERT INTO comment_reaction(comment_id,author_pl_id) VALUES(?,?)').bind(id,authorId).run();return!old}
async function deleteCommentTree(db,id){const rows=await db.prepare(`WITH RECURSIVE d(id) AS (SELECT comment_id FROM comment WHERE comment_id=? UNION ALL SELECT c.comment_id FROM comment c JOIN d ON c.parent_comment_id=d.id) SELECT id FROM d`).bind(id).all();const ids=(rows.results||[]).map(r=>r.id).reverse();for(const x of ids)await db.prepare('DELETE FROM comment WHERE comment_id=?').bind(x).run()}

const matrixStateId=id=>`__matrix_state__:${id}`;
async function getMatrix(env,roomId){const row=await env.DB.prepare('SELECT template_definition,updated_at FROM matrix_template WHERE template_id=? AND room_id=?').bind(matrixStateId(roomId),roomId).first();let state={};try{state=row?JSON.parse(row.template_definition||'{}'): {}}catch{};if(!state||typeof state!=='object')state={};state.items=state.items&&typeof state.items==='object'?state.items:{};const pts=(await env.DB.prepare('SELECT point_id,is_placed,point_x,point_y,template_x,template_y,scale_base_width,coordinate_version,supplement_body FROM matrix_point WHERE room_id=?').bind(roomId).all()).results||[];for(const p of pts){const x=state.items[p.point_id]&&typeof state.items[p.point_id]==='object'?state.items[p.point_id]:{};x.placed=!!p.is_placed;if(p.point_x!==null)x.x=Number(p.point_x);if(p.point_y!==null)x.y=Number(p.point_y);if(p.template_x!==null)x.templateX=Number(p.template_x);if(p.template_y!==null)x.templateY=Number(p.template_y);if(p.scale_base_width!==null)x.scaleBaseWidth=Number(p.scale_base_width);x.coordVersion=Number(p.coordinate_version)||0;if(p.supplement_body)x.supplement=p.supplement_body;state.items[p.point_id]=x}return{state,updatedAt:row?.updated_at||''}}
async function putMatrix(env,roomId,state){const serialized=JSON.stringify(state||{});if(serialized.length>1_500_000)throw Object.assign(new Error('MATRIXの保存データが大きすぎます'),{status:413});const id=matrixStateId(roomId);await env.DB.prepare(`INSERT INTO matrix_template(template_id,room_id,template_name,template_definition,updated_at) VALUES(?,?,?, ?,CURRENT_TIMESTAMP) ON CONFLICT(template_id) DO UPDATE SET template_definition=excluded.template_definition,updated_at=CURRENT_TIMESTAMP`).bind(id,roomId,'__STATE__',serialized).run()}

const sheetId=id=>`sheet:${id}`,sheetStateId=id=>`sheet-state:${id}`;
async function getSheet(env,roomId){const row=await env.DB.prepare(`SELECT c.cell_value,c.updated_at FROM spreadsheet s LEFT JOIN spreadsheet_cell c ON c.sheet_id=s.sheet_id AND c.cell_id=? WHERE s.room_id=? ORDER BY s.created_at LIMIT 1`).bind(sheetStateId(roomId),roomId).first();let state=null;try{state=row?.cell_value?JSON.parse(row.cell_value):null}catch{}return{state,updatedAt:row?.updated_at||''}}
async function putSheet(env,roomId,state){const text=JSON.stringify(state||{});if(text.length>1_500_000)throw Object.assign(new Error('Spreadsheetの保存データが大きすぎます'),{status:413});const sid=sheetId(roomId);await env.DB.prepare(`INSERT INTO spreadsheet(sheet_id,room_id,sheet_name,row_count,column_count,updated_at) VALUES(?,?,?,0,0,CURRENT_TIMESTAMP) ON CONFLICT(sheet_id) DO UPDATE SET updated_at=CURRENT_TIMESTAMP`).bind(sid,roomId,String(state?.name||state?.title||'Spreadsheet').slice(0,120)).run();await env.DB.prepare(`INSERT INTO spreadsheet_cell(cell_id,sheet_id,row_index,column_index,cell_value,cell_type,cell_style,updated_at) VALUES(?,?,-1,-1,?,'state','{}',CURRENT_TIMESTAMP) ON CONFLICT(cell_id) DO UPDATE SET cell_value=excluded.cell_value,updated_at=CURRENT_TIMESTAMP`).bind(sheetStateId(roomId),sid,text).run()}

async function profileTransfer(ctx,parts){const {request,env}=ctx;if(request.method==='POST'&&parts.length===1){const b=await safeBody(request),p=b?.profile;if(!p?.id||!p?.plName)return json({error:'PL情報が足りません'},400);await ensurePlIdentity(env.DB,String(p.id),String(p.plName));for(const x of Array.isArray(p.personas)?p.personas:[])await resolveCharacterIdentity(env.DB,String(p.id),String(x?.name||''),String(x?.type||'PC'),{characterId:x?.id});let code='';for(let i=0;i<32&&!code;i++){const c=String(crypto.getRandomValues(new Uint32Array(1))[0]%10000).padStart(4,'0');if(!await env.DB.prepare('SELECT 1 FROM transfer WHERE transfer_code_hash=? AND transfer_used_at IS NULL').bind(await tokenHash(c)).first())code=c}if(!code)return json({error:'引き継ぎコードを発行できませんでした。もう一度お試しください。'},503);const exp=new Date(Date.now()+30*60*1000).toISOString();await env.DB.prepare('INSERT INTO transfer(transfer_id,pl_id,transfer_code_hash,transfer_expires_at) VALUES(?,?,?,?)').bind(`profile_${randomToken(14)}`,String(p.id),await tokenHash(code),exp).run();return json({code,expiresAt:exp})}if(request.method==='POST'&&parts[1]){const row=await env.DB.prepare("SELECT * FROM transfer WHERE transfer_id LIKE 'profile_%' AND transfer_code_hash=?").bind(await tokenHash(String(parts[1]).padStart(4,'0'))).first();if(!row||row.transfer_used_at)return json({error:'コードが無効、または使用済みです'},404);if(Date.parse(row.transfer_expires_at)<=Date.now())return json({error:'コードの有効期限（30分）が切れています'},410);await env.DB.prepare('UPDATE transfer SET transfer_used_at=CURRENT_TIMESTAMP WHERE transfer_id=?').bind(row.transfer_id).run();const pl=await env.DB.prepare('SELECT * FROM pl WHERE pl_id=?').bind(row.pl_id).first(),chars=(await env.DB.prepare('SELECT * FROM character WHERE pl_id=?').bind(row.pl_id).all()).results||[];return json({profile:{id:pl.pl_id,plName:pl.pl_name,plIcon:iconUrl(pl.pl_icon_key),plColor:pl.pl_color,personas:chars.map(c=>({id:c.character_id,name:c.character_name,type:c.character_type,icon:iconUrl(c.character_icon_key),color:c.character_color}))}})}return null}

export async function onRequest(ctx){
  const {request,env,params}=ctx;if(!env.DB)return json({error:'D1データベースが接続されていません'},500);await ensureSchema(env.DB);
  const parts=Array.isArray(params.path)?params.path:String(params.path||'').split('/').filter(Boolean),method=request.method;
  if(parts[0]==='profile-transfers'){const r=await profileTransfer(ctx,parts);if(r)return r}

  if(parts[0]==='boards'){
    if(method==='POST'&&parts.length===1){const b=await safeBody(request),name=String(b?.name||'').trim().slice(0,120),owner=String(b?.ownerId||'').slice(0,120);if(!name)return json({error:'自陣の名前を入力してください'},400);if(!owner)return json({error:'作成者情報がありません'},400);await ensurePlIdentity(env.DB,owner,String(b?.ownerName||'PL'));const id=randomToken(20),adminToken=randomToken(24);await env.DB.prepare('INSERT INTO room(room_id,owner_pl_id,room_name,room_admin_token_hash) VALUES(?,?,?,?)').bind(id,owner,name,await tokenHash(adminToken)).run();return json({id,adminToken,name},201)}
    const roomId=String(parts[1]||''),room=roomId?await ensureRoom(env.DB,roomId):null;if(!room)return json({error:'自陣の部屋が見つかりません'},404);
    if(method==='GET'&&parts.length===2)return json(await roomPayload(env,room));
    if(parts[2]==='spreadsheet'&&parts[3]==='state'&&parts.length===4){if(method==='GET')return json(await getSheet(env,roomId));if(method==='POST'){const b=await safeBody(request);try{await putSheet(env,roomId,b?.state);return json({ok:true})}catch(e){return json({error:e.message},e.status||500)}}}
    if(parts[2]==='matrix'&&parts[3]&&parts.length===4){const log=await ensureLog(env.DB,parts[3]);if(!log||log.room_id!==roomId)return json({error:'この自陣にないログです'},404);if(method==='GET'){const m=await getMatrix(env,roomId),cs=await commentRows(env,roomId,'','matrix_template',matrixStateId(roomId));return json({state:m.state,updatedAt:m.updatedAt,comments:cs.map(c=>({id:c.comment_id,author_id:c.author_pl_id,author_name:c.pl_name,body:c.comment_body,created_at:c.created_at}))})}if(method==='POST'){const b=await safeBody(request),aid=String(b?.authorId||''),an=String(b?.authorName||'').trim();if(!aid||!an)return json({error:'先に発言者を登録してください'},400);await ensurePlIdentity(env.DB,aid,an);try{if(b?.state!==undefined)await putMatrix(env,roomId,b.state)}catch(e){return json({error:e.message},e.status||500)}const text=String(b?.comment||'').trim().slice(0,2000);if(text)await env.DB.prepare("INSERT INTO comment(comment_id,room_id,author_pl_id,comment_target_type,comment_target_id,comment_body) VALUES(?,?,?,'matrix_template',?,?)").bind(randomToken(16),roomId,aid,matrixStateId(roomId),text).run();return json({ok:true})}}
    if(parts[2]==='matrix'&&parts[3]&&parts[4]==='comments'){const log=await ensureLog(env.DB,parts[3]);if(!log||log.room_id!==roomId)return json({error:'この自陣にないログです'},404);const cid=String(parts[5]||''),action=String(parts[6]||'');if(method==='GET'&&!cid){const viewer=new URL(request.url).searchParams.get('authorId')||'',rows=[...await commentRows(env,roomId,viewer,'matrix_point'),...await commentRows(env,roomId,viewer,'matrix_template')].sort((a,b)=>String(a.created_at).localeCompare(String(b.created_at)));return json({comments:rows.map(c=>({id:c.comment_id,target_id:c.comment_target_id,parent_id:c.parent_comment_id||'',author_id:c.author_pl_id,author_name:c.pl_name,persona_name:c.character_name||c.pl_name,persona_type:c.character_type||'PL',persona_icon:iconUrl(c.character_icon_key||c.pl_icon_key),body:c.comment_body,created_at:c.created_at,updated_at:c.updated_at,like_count:Number(c.like_count)||0,liked_by_me:!!c.liked_by_me}))})}if(method==='POST'&&!cid){const b=await safeBody(request),target=String(b?.targetId||'').slice(0,180),text=String(b?.body||'').trim().slice(0,4000),parent=String(b?.parentId||'').slice(0,120);if(!target||!text)return json({error:'コメント情報が足りません'},400);const who=await identity(env,b);if(!who.plId)return json({error:'コメント情報が足りません'},400);const type=target.includes('@@matrix-template@@')?'matrix_template':'matrix_point',id=randomToken(16);await env.DB.prepare("INSERT INTO comment(comment_id,room_id,author_pl_id,author_character_id,comment_target_type,comment_target_id,comment_body,parent_comment_id) VALUES(?,?,?,?,?,?,?,NULLIF(?,''))").bind(id,roomId,who.plId,who.characterId,type,target,text,parent).run();notify(ctx,roomId,'matrix-comment');return json({id},201)}if(method==='POST'&&cid&&action==='like'){const b=await safeBody(request),liked=await toggleReaction(env,cid,String(b?.authorId||''));if(liked===null)return json({error:'参加者情報が必要です'},400);notify(ctx,roomId,'matrix-like');return json({liked})}if((method==='PATCH'||method==='DELETE')&&cid){const b=await safeBody(request),row=await env.DB.prepare('SELECT author_pl_id FROM comment WHERE comment_id=? AND room_id=?').bind(cid,roomId).first();if(!row)return json({error:'コメントが見つかりません'},404);if(row.author_pl_id!==String(b?.authorId||''))return json({error:`自分のコメントだけ${method==='PATCH'?'編集':'削除'}できます`},403);if(method==='PATCH'){const text=String(b?.body||'').trim().slice(0,4000);if(!text)return json({error:'感想を入力してください'},400);await env.DB.prepare('UPDATE comment SET comment_body=?,updated_at=CURRENT_TIMESTAMP WHERE comment_id=?').bind(text,cid).run();notify(ctx,roomId,'matrix-edit');return json({ok:true})}await deleteCommentTree(env.DB,cid);notify(ctx,roomId,'matrix-delete');return json({ok:true})}}
    if(!await verifyRoomAdmin(env.DB,roomId,request.headers.get('x-board-admin-token')||''))return json({error:'この自陣を編集できるのは部屋主だけです'},403);
    if(method==='PATCH'&&parts.length===2){const b=await safeBody(request),name=String(b?.name||'').trim().slice(0,120);if(!name)return json({error:'自陣の名前を入力してください'},400);await env.DB.prepare('UPDATE room SET room_name=?,updated_at=CURRENT_TIMESTAMP WHERE room_id=?').bind(name,roomId).run();return json({ok:true,name})}
    if(method==='PATCH'&&parts[2]==='logs'&&parts[3]&&parts.length===4){const b=await safeBody(request),r=await env.DB.prepare('UPDATE log SET spoiler_enabled=?,scenario_title=?,updated_at=CURRENT_TIMESTAMP WHERE room_id=? AND log_id=?').bind(b?.spoiler?1:0,String(b?.scenarioTitle||'').trim().slice(0,120),roomId,parts[3]).run();return r.meta?.changes?json({ok:true}):json({error:'ログが見つかりません'},404)}
    if(method==='POST'&&parts[2]==='logs'&&parts.length===3){const b=await safeBody(request),id=String(b?.roomId||''),l=await ensureLog(env.DB,id);if(!l||l.room_id!==roomId)return json({error:'追加するログが見つかりません'},404);if(b?.scenarioTitle!==undefined||b?.spoiler!==undefined)await env.DB.prepare('UPDATE log SET spoiler_enabled=?,scenario_title=?,updated_at=CURRENT_TIMESTAMP WHERE log_id=?').bind(b?.spoiler?1:0,String(b?.scenarioTitle||'').trim().slice(0,120),id).run();return json({ok:true,roomId:id},201)}
    if(method==='DELETE'&&parts[2]==='logs'&&parts[3]&&parts.length===4){const l=await ensureLog(env.DB,parts[3]);if(!l||l.room_id!==roomId)return json({error:'ログが見つかりません'},404);await deleteR2Prefix(env.LOGS,`rooms/${roomId}/logs/${parts[3]}/`).catch(()=>{});await env.DB.prepare('DELETE FROM log WHERE log_id=?').bind(parts[3]).run();notify(ctx,roomId,'log-delete');return json({ok:true})}
  }

  if(parts[0]==='rooms'&&parts[1]){
    const logId=String(parts[1]),log=await ensureLog(env.DB,logId);if(!log)return json({error:'部屋が見つかりません'},404);const roomId=log.room_id;
    if(method==='GET'&&parts.length===2&&new URL(request.url).searchParams.get('summary')==='1')return json({id:log.log_id,title:log.log_name,createdAt:log.log_created_at});
    if(method==='DELETE'&&parts.length===2){await env.DB.prepare('DELETE FROM log WHERE log_id=?').bind(logId).run();notify(ctx,roomId,'log-delete');return json({ok:true})}
    if(method==='GET'&&parts[2]==='realtime'&&parts.length===3){if(request.headers.get('Upgrade')?.toLowerCase()!=='websocket')return json({error:'WebSocket接続が必要です'},426);const hub=roomHub(env,roomId);return hub?hub.fetch(new Request(new URL('/realtime',request.url),request)):json({error:'リアルタイム機能が接続されていません（Binding名: ROOMS）'},503)}
    if(parts[2]==='presence'){const hub=roomHub(env,roomId);if(!hub)return json({presence:[]});if(method==='GET')return hub.fetch('https://room/presence');if(method==='POST')return hub.fetch('https://room/presence',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(await safeBody(request)||{})})}
    if(method==='GET'&&parts[2]==='icons'&&parts[3]){for(const prefix of ['pl-icons','character-icons','matrix-icons']){const object=await env.LOGS?.get(`${prefix}/${parts[3]}`);if(object)return new Response(object.body,{headers:{'content-type':object.httpMetadata?.contentType||'image/webp','cache-control':'private, max-age=31536000, immutable'}})}return new Response('Not found',{status:404})}
    if(parts[2]==='annotations'){
      const cid=String(parts[3]||''),action=String(parts[4]||'');
      if(method==='GET'&&cid&&action==='image'){const row=await env.DB.prepare('SELECT comment_image_key FROM comment WHERE comment_id=? AND room_id=?').bind(cid,roomId).first(),object=row?.comment_image_key?await env.LOGS?.get(row.comment_image_key):null;return object?new Response(object.body,{headers:{'content-type':object.httpMetadata?.contentType||'image/webp'}}):new Response('Not found',{status:404})}
      if(method==='GET'&&cid==='version'){const r=await ensureRoom(env.DB,roomId);return json({version:Number(r?.room_revision)||0})}
      if(method==='GET'&&!cid){const viewer=new URL(request.url).searchParams.get('authorId')||'',rows=await commentRows(env,roomId,viewer,'log_range',logId),ranges=(await env.DB.prepare("SELECT * FROM log_comment_range WHERE comment_id IN (SELECT comment_id FROM comment WHERE room_id=? AND comment_target_type='log_range' AND comment_target_id=?)").bind(roomId,logId).all()).results||[],rm=new Map(ranges.map(r=>[r.comment_id,r])),rr=await ensureRoom(env.DB,roomId);return json({annotations:rows.map(c=>{const r=rm.get(c.comment_id)||{};return{id:c.comment_id,room_id:logId,message_id:r.start_line_id||'',end_message_id:r.end_line_id||r.start_line_id||'',parent_id:c.parent_comment_id||'',start_offset:Number(r.start_character_offset)||0,end_offset:Number(r.end_character_offset)||0,quote:r.selected_text||'',color:r.marker_color||'yellow',author_id:c.author_pl_id,author_name:c.pl_name,persona_name:c.character_name||c.pl_name,persona_type:c.character_type||'PL',persona_icon:iconUrl(c.character_icon_key||c.pl_icon_key),body:c.comment_body,created_at:c.created_at,updated_at:c.updated_at,has_image:c.comment_image_key?1:0,like_count:Number(c.like_count)||0,liked_by_me:!!c.liked_by_me}}),version:Number(rr?.room_revision)||0})}
      if(method==='POST'&&!cid){const b=await safeBody(request),required=['messageId','quote','authorName','personaName','personaType'],missing=!b?required:required.filter(k=>b[k]==null||String(b[k]).trim()==='');if(missing.length)return json({error:`入力が足りません（${missing.join(', ')}）`},400);const text=String(b.body||'').trim();if(!text)return json({error:'感想を入力してください'},400);const who=await identity(env,b),id=randomToken(16);await env.DB.batch([env.DB.prepare("INSERT INTO comment(comment_id,room_id,author_pl_id,author_character_id,comment_target_type,comment_target_id,comment_body,parent_comment_id) VALUES(?,?,?,?,'log_range',?,?,NULLIF(?,''))").bind(id,roomId,who.plId,who.characterId,logId,text,String(b.parentId||'')),env.DB.prepare('INSERT INTO log_comment_range(comment_id,start_line_id,start_character_offset,end_line_id,end_character_offset,selected_text,marker_color) VALUES(?,?,?,?,?,?,?)').bind(id,String(b.messageId),Number(b.startOffset)||0,String(b.endMessageId||b.messageId),Number(b.endOffset)||0,String(b.quote).slice(0,2000),String(b.color||'yellow').slice(0,40))]);await bumpRoomRevision(env.DB,roomId);notify(ctx,roomId,'comment');return json({id},201)}
      if(method==='POST'&&cid&&action==='like'){const b=await safeBody(request),liked=await toggleReaction(env,cid,String(b?.authorId||''));if(liked===null)return json({error:'参加者情報が必要です'},400);await bumpRoomRevision(env.DB,roomId);notify(ctx,roomId,'like');return json({liked})}
      if(method==='DELETE'&&cid){const b=await safeBody(request),c=await env.DB.prepare('SELECT author_pl_id FROM comment WHERE comment_id=? AND room_id=?').bind(cid,roomId).first();if(!c)return json({error:'コメントが見つかりません'},404);const admin=await verifyRoomAdmin(env.DB,roomId,request.headers.get('x-admin-token')||'');if(!admin&&String(b?.authorId||'')!==c.author_pl_id)return json({error:'自分のコメントだけ削除できます'},403);await deleteCommentTree(env.DB,cid);await bumpRoomRevision(env.DB,roomId);notify(ctx,roomId,'delete');return json({ok:true})}
      if(method==='PATCH'&&cid&&cid!=='color'){const b=await safeBody(request),c=await env.DB.prepare('SELECT author_pl_id,comment_image_key FROM comment WHERE comment_id=? AND room_id=?').bind(cid,roomId).first();if(!c)return json({error:'コメントが見つかりません'},404);if(String(b?.authorId||'')!==c.author_pl_id)return json({error:'自分のコメントだけ編集できます'},403);const text=String(b?.body||'').trim().slice(0,4000);let imageKey=c.comment_image_key||null;if(b?.imageData!==undefined&&b?.imageData!==null)imageKey=String(b.imageData||'')?await storeImage(env.LOGS,String(b.imageData),'comment-images'):null;if(!text&&!imageKey)return json({error:'感想または画像を入力してください'},400);await env.DB.prepare('UPDATE comment SET comment_body=?,comment_image_key=?,updated_at=CURRENT_TIMESTAMP WHERE comment_id=?').bind(text,imageKey,cid).run();await env.DB.prepare('UPDATE log_comment_range SET marker_color=? WHERE comment_id=?').bind(String(b?.color||'yellow').slice(0,40),cid).run();await bumpRoomRevision(env.DB,roomId);notify(ctx,roomId,'edit');return json({ok:true})}
      if(method==='PATCH'&&cid==='color'){const b=await safeBody(request),author=String(b?.authorId||''),name=String(b?.personaName||''),type=String(b?.personaType||'PL').toUpperCase(),color=String(b?.color||'');if(!author||!name||!color)return json({error:'色の更新情報が足りません'},400);if(type==='PL')await env.DB.prepare("UPDATE log_comment_range SET marker_color=? WHERE comment_id IN (SELECT comment_id FROM comment WHERE room_id=? AND comment_target_type='log_range' AND comment_target_id=? AND author_pl_id=? AND author_character_id IS NULL)").bind(color.slice(0,40),roomId,logId,author).run();else{const ch=await env.DB.prepare('SELECT character_id FROM character WHERE pl_id=? AND character_name=? AND character_type=? LIMIT 1').bind(author,name,type==='NPC'?'NPC':'PC').first();if(ch)await env.DB.prepare("UPDATE log_comment_range SET marker_color=? WHERE comment_id IN (SELECT comment_id FROM comment WHERE room_id=? AND comment_target_type='log_range' AND comment_target_id=? AND author_pl_id=? AND author_character_id=?)").bind(color.slice(0,40),roomId,logId,author,ch.character_id).run()}await bumpRoomRevision(env.DB,roomId);notify(ctx,roomId,'color');return json({ok:true})}
    }
  }
  return json({error:'Not found'},404);
}
