import { parentRoomForLog,ensurePlIdentity } from './data-model.js';
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const finite=(value,fallback=null)=>{const n=Number(value);return Number.isFinite(n)?n:fallback};
export async function handleMatrixPoint(request,env,roomId,logId,itemId){
  if(request.method!=='PATCH')return json({error:'Method not allowed'},405);if(!roomId||!logId||!itemId)return json({error:'座標情報が足りません'},400);const log=await parentRoomForLog(env.DB,logId);if(!log||log.room_id!==roomId)return json({error:'この自陣にないログです'},404);
  let body=null;try{body=await request.json()}catch{}const authorId=String(body?.authorId||'').slice(0,120),authorName=String(body?.authorName||'').trim().slice(0,80);if(!authorId||!authorName)return json({error:'先に発言者を登録してください'},400);await ensurePlIdentity(env.DB,authorId,authorName);
  const old=await env.DB.prepare('SELECT * FROM matrix_point WHERE point_id=? AND room_id=?').bind(itemId,roomId).first(),placed=body?.placed!==undefined?!!body.placed:!!old?.is_placed,x=finite(body?.x,old?.point_x??null),y=finite(body?.y,old?.point_y??null),templateX=finite(body?.templateX,old?.template_x??null),templateY=finite(body?.templateY,old?.template_y??null),scale=finite(body?.scaleBaseWidth,old?.scale_base_width??null),version=Math.max(0,Math.min(10,Math.trunc(finite(body?.coordVersion,old?.coordinate_version??0))));const ch=await env.DB.prepare('SELECT character_id FROM character WHERE character_id=?').bind(itemId).first();
  await env.DB.prepare(`INSERT INTO matrix_point(point_id,room_id,character_id,is_placed,point_x,point_y,template_x,template_y,scale_base_width,coordinate_version,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(point_id) DO UPDATE SET room_id=excluded.room_id,character_id=COALESCE(excluded.character_id,matrix_point.character_id),is_placed=excluded.is_placed,point_x=excluded.point_x,point_y=excluded.point_y,template_x=excluded.template_x,template_y=excluded.template_y,scale_base_width=excluded.scale_base_width,coordinate_version=excluded.coordinate_version,updated_at=CURRENT_TIMESTAMP`).bind(itemId,roomId,ch?.character_id||null,placed?1:0,x,y,templateX,templateY,scale,version).run();
  return json({ok:true,point:{itemId,placed,x,y,templateX,templateY,coordVersion:version,scaleBaseWidth:scale}});
}
